name: Hello world
author: Robin
description: Some desc
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Rob
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet}}
